export const ALL_CONTENT_REQUEST = "ALL_CONTENT_REQUEST";
export const ALL_CONTENT_SUCCESS = "ALL_CONTENT_SUCCESS";
export const ALL_CONTENT_FAIL = "ALL_CONTENT_FAIL";

export const MY_CONTENT_REQUEST = "MY_CONTENT_REQUEST";
export const MY_CONTENT_SUCCESS = "MY_CONTENT_SUCCESS";
export const MY_CONTENT_FAIL = "MY_CONTENT_FAIL";

export const MY_CONTENT_TO_VERIFY_REQUEST = "MY_CONTENT_TO_VERIFY_REQUEST";
export const MY_CONTENT_TO_VERIFY_SUCCESS = "MY_CONTENT_TO_VERIFY_SUCCESS";
export const MY_CONTENT_TO_VERIFY_FAIL = "MY_CONTENT_TO_VERIFY_FAIL";

export const TOPIC_CONTENT_REQUEST = "TOPIC_CONTENT_REQUEST";
export const TOPIC_CONTENT_SUCCESS = "TOPIC_CONTENT_SUCCESS";
export const TOPIC_CONTENT_FAIL = "TOPIC_CONTENT_FAIL";

